Improve Check-System

diff --git a/VMMgr_Libs/VMMgr_Functions b/VMMgr_Libs/VMMgr_Functions
--- a/VMMgr_Libs/VMMgr_Functions
+++ b/VMMgr_Libs/VMMgr_Functions
@@ -7,6 +7,7 @@
 #
 # Functions:
 # Check_Softwares: try to check if all required software are installed
+# Check_Sudo: Check sudo rules
 # Check_Requirements: Helper for hypervisor configuration
 # Check_System: Check system requirements
 # Check_MEM: calculate and/or check MEM and MAXMEM
@@ -52,70 +53,108 @@ function Check_Softwares() {
     fi
 }
 
+# Function: Check_Sudo
+# Description: Check sudo rules
+# Args: None
+function Check_Sudo() {
+    SUDOOK="0"
+    for SUDOCMD in $(echo "/usr/sbin/ip /usr/sbin/brctl /usr/bin/ovs-vsctl /usr/bin/nmcli /usr/sbin/setcap /usr/bin/systemctl /usr/bin/cat /usr/bin/chmod /usr/bin/chown /usr/sbin/modprobe /usr/sbin/setcap /usr/bin/mkdir"); do
+        RESULT=$(sudo -l $SUDOCMD 2>&1)
+        if [ "$RESULT" == "" ]; then
+            SUDOOK=1
+            break;
+        elif [ "${RESULT#sudo}" != "$RESULT" ]; then
+             continue
+        elif [ "$SUDOCMD" == "$RESULT" ]; then
+            continue
+        else
+            SUDOOK=1
+            break;
+        fi
+    done
+    echo $RESULT
+}
+
 # Function: Check_Requirements
 # Description: Helper for hypervisor configuration
-# Args: no
+# Args: None
 function Check_Requirements() {
     echo "Checking..."
     echo ""
-    PACKAGES=$(Check_Softwares "qemu-system-x86|sqlite edk2-ovmf|virt-viewer" 0)
-    if [ "$PACKAGES" ]; then
-        echo "You must install the following packages: $PACKAGES"
-        echo ""
-    fi
-    PACKAGES=$(Check_Softwares "NetworkManager|openvswitch|virglrenderer|dpdk" 0)
-    if [ "$PACKAGES" ]; then
-        echo "You can install the following optionals packages: $PACKAGES"
-        echo ""
-    fi
-    PACKAGES=$(Check_Softwares "ulatencyd" 1)
-    if [ "$PACKAGES" ]; then
-        echo "You should delete following packages: $PACKAGES"
-        echo ""
-    fi
     
-    if [ "$(getent group qemu)" == "" ]; then
-        echo "You must create group 'qemu'"
-        echo "kvm user must in this group too"
+    SUDOOK=$(Check_Sudo)
+    if [ "$SUDOOK" == "1" ]; then
+        echo "### Step 1: install sudo rules:"
+    
+        echo "Sudoers: You must set the following rules:"
+        echo "Cmnd_Alias VMMGRCMD= /usr/sbin/ip, /usr/sbin/brctl, /usr/bin/ovs-vsctl, /usr/bin/nmcli, /usr/sbin/setcap, /usr/bin/systemctl, /usr/bin/cat, /usr/bin/chmod, /usr/bin/chown, /usr/sbin/modprobe, /usr/sbin/setcap, /usr/bin/mkdir"
+        echo "Cmnd_Alias VMMGRCHECK= /usr/bin/ls"
+    
+        echo "%qemu ALL=(root:root) NOPASSWD: VMMGRCMD"
+        echo "%qemu ALL=(qemu:qemu) NOPASSWD: VMMGRCHECK"
         echo ""
-    fi
     
-    echo "Sudoers: You must set the following rules:"
-    echo "Cmnd_Alias VMMGRCMD= /usr/sbin/ip, /usr/sbin/brctl, /usr/bin/ovs-vsctl, /usr/bin/nmcli, /usr/sbin/setcap, /usr/bin/systemctl"
-    echo "%qemu ALL=(root:root) NOPASSWD: VMMGRCMD"
-    echo ""
-    
-    ISOPATH=$(sudo -u qemu ls -l $VMMGR_ISO_PATH 2>/dev/null)
-    if [ "$ISOPATH" == "" ]; then
-        echo "If you plan to use systemd, you ISO PATH ($VMMGR_ISO_PATH) must be readable by qemu user"
-        echo ""
-    fi
-    
-    echo "DISKPATH: if you plan to use systemd, your DISKPATH var in your VM configs must be readable by qemu user"
-    echo ""
-    
-    for KERNELOPT in $(echo "nodelayacct transparent_hugepage=madvise elevator=deadline kvm-intel.nested=1 iommu=1 intel_iommu=on kvm-intel.ept=1"); do
-        if [ "$(cat /proc/cmdline | grep $KERNELOPT)" == "" ]; then
-            OPTIONS="$OPTIONS $KERNELOPT"
+    else
+        PACKAGES=$(Check_Softwares "qemu-system-x86|sqlite edk2-ovmf|virt-viewer" 0)
+        if [ "$PACKAGES" ]; then
+            echo "You must install the following packages: $PACKAGES"
+            echo ""
         fi
-    done
-    if [ "$OPTIONS" ]; then
-        echo "You should add the following kernel options in your grub.cfg:"
-        echo $OPTIONS
+        PACKAGES=$(Check_Softwares "NetworkManager|openvswitch|virglrenderer|dpdk" 0)
+        if [ "$PACKAGES" ]; then
+            echo "You can install the following optionals packages: $PACKAGES"
+            echo ""
+        fi
+        PACKAGES=$(Check_Softwares "ulatencyd" 1)
+        if [ "$PACKAGES" ]; then
+            echo "You should delete following packages: $PACKAGES"
+            echo ""
+        fi
+    
+        if [ "$(getent group qemu | grep $(whoami) | grep qemu)" == "" ]; then
+            echo "you account must be member of qemu group:"
+            echo "> usermod -a -G qemu $(whoami)"
+        fi
+        
+        if [ "$(getent group kvm | grep qemu)" == "" ]; then
+            echo "qemu user must be member of kvm group:"
+            echo "> usermod -a -G kvm qemu"
+        fi
+    
+        ISOPATH=$(sudo -u qemu ls -l $VMMGR_ISO_PATH 2>/dev/null)
+        if [ "$ISOPATH" == "" ]; then
+            echo "If you plan to use systemd, you ISO PATH ($VMMGR_ISO_PATH) must be readable by qemu user"
+            echo "> chown -R :qemu $VMMGR_ISO_PATH && chmod 750 $VMMGR_ISO_PATH"
+        fi
+    
+        echo "DISKPATH: if you plan to use systemd, your DISKPATH var in your VM configs must be readable by qemu user"
         echo ""
-    fi
+    
+        for KERNELOPT in $(echo "nodelayacct transparent_hugepage=madvise elevator=deadline kvm-intel.nested=1 iommu=1 intel_iommu=on kvm-intel.ept=1"); do
+            if [ "$(cat /proc/cmdline | grep $KERNELOPT)" == "" ]; then
+                OPTIONS="$OPTIONS $KERNELOPT"
+            fi
+        done
 
-    if [ "$(tuned-adm list | grep hypervisor)" == "" ]; then
-        echo "You should install tuned profile provided by copying Configs/tuned.conf in /etc/tuned/hypervisor/"
-        echo ""
-    fi
+        if [ "$OPTIONS" ]; then
+            echo "You should add the following kernel options in your grub.cfg:"
+            echo $OPTIONS
+            echo ""
+        fi
+
+        if [ "$(tuned-adm list | grep hypervisor)" == "" ]; then
+            echo "You should install tuned profile provided by copying Configs/tuned.conf in /etc/tuned/hypervisor/"
+            echo ""
+        fi
     
-    if [ "$(tuned-adm active | grep hypervisor)" == "" ]; then
-        echo "tuned profile hypervisor is not active!"
-        echo ""
-    fi
+        if [ "$(tuned-adm active | grep hypervisor)" == "" ]; then
+            echo "tuned profile hypervisor is not active!"
+            echo ""
+        fi
     
-    echo "SPICE/VNC secure mode: make sure keys and certificates are readable by qemu user and/or group"
+        echo "SPICE/VNC secure mode: make sure keys and certificates are readable by qemu user and/or group"
+        Check_System
+    fi
 }
 
 # Function: Check_System
@@ -126,45 +165,50 @@ function Check_Requirements() {
 #   2: Check perms on /dev/net/tun, /dev/vhost-net and /dev/kvm
 #   3: Set cap_net_admin on qemu-system_x86_64
 function Check_System() {
-    if [ "$(modinfo vhost-net -F intree)" != "Y" ]; then
-        sudo modprobe vhost vhost-net
-    fi
+    SUDOOK=$(Check_Sudo)
+    if [ "$SUDOOK" == "1" ]; then
+        if [ "$(modinfo vhost-net -F intree)" != "Y" ]; then
+            sudo modprobe vhost vhost-net
+        fi
     
-    ls -l /dev/net/tun | cut -d\  -f1 | grep 'crw-rw-rw-' > /dev/null
-    if [ $? -ne 0 ]; then
-        sudo chmod 0666 /dev/net/tun
-    fi
+        ls -l /dev/net/tun | cut -d\  -f1 | grep 'crw-rw-rw-' > /dev/null
+        if [ $? -ne 0 ]; then
+            sudo chmod 0666 /dev/net/tun
+        fi
 
-    ls -l /dev/vhost-net | cut -d\  -f1 | grep 'crw-rw-rw-' > /dev/null
-    if [ $? -ne 0 ]; then
-        sudo chmod 0666 /dev/vhost-net
-    fi
+        ls -l /dev/vhost-net | cut -d\  -f1 | grep 'crw-rw-rw-' > /dev/null
+        if [ $? -ne 0 ]; then
+            sudo chmod 0666 /dev/vhost-net
+        fi
 
-    ls -l /dev/kvm | cut -d\  -f1 | grep 'crw-rw-rw-' > /dev/null
-    if [ $? -ne 0 ]; then
-        sudo chmod 0666 /dev/kvm
-    fi
+        ls -l /dev/kvm | cut -d\  -f1 | grep 'crw-rw-rw-' > /dev/null
+        if [ $? -ne 0 ]; then
+            sudo chmod 0666 /dev/kvm
+        fi
 
-    getcap /usr/bin/qemu-system-x86_64 | grep cap_net_admin+ep > /dev/null
-    if [ $? -ne 0 ]; then
-        sudo setcap cap_net_admin+ep /usr/bin/qemu-system-x86_64
-    fi
+        getcap /usr/bin/qemu-system-x86_64 | grep cap_net_admin+ep > /dev/null
+        if [ $? -ne 0 ]; then
+            sudo setcap cap_net_admin+ep /usr/bin/qemu-system-x86_64
+        fi
     
-    # On a besoin de voir comment faire dans sudo pour que ça fonctionne
-    #if [ $(cat /proc/sys/net/ipv4/ip_forward) -eq 0 ]; then
-        #sudo echo 1 > /proc/sys/net/ipv4/ip_forward
-    #fi
+        # On a besoin de voir comment faire dans sudo pour que ça fonctionne
+        #if [ $(cat /proc/sys/net/ipv4/ip_forward) -eq 0 ]; then
+            #sudo echo 1 > /proc/sys/net/ipv4/ip_forward
+        #fi
     
-    modinfo openvswitch 2>/dev/null 1>/dev/null
-    if [ $? -eq 0 ]; then
-        sudo modprobe openvswitch
-        [ -d /run/openvswitch ] || sudo mkdir /run/openvswitch
-    fi
+        modinfo openvswitch 2>/dev/null 1>/dev/null
+        if [ $? -eq 0 ]; then
+            sudo modprobe openvswitch
+            [ -d /run/openvswitch ] || sudo mkdir /run/openvswitch
+        fi
     
-    if [ ! -r "/run/VMMGR" ]; then
-        sudo mkdir /run/VMMGR 
-        sudo chown -R qemu:qemu /run/VMMGR
-        sudo chmod -R 770 /run/VMMGR
+        if [ ! -r "/run/VMMGR" ]; then
+            sudo mkdir /run/VMMGR 
+            sudo chown -R qemu:qemu /run/VMMGR
+            sudo chmod -R 770 /run/VMMGR
+        fi
+    else
+        echo "Unable to Check System, please verify sudo rules"
     fi
 }
 
